apps/apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import theme.views
import dziennik_posilkow.urls

urlpatterns = [
    url(r'^$', theme.views.home, name='home'),
    url(r'^dziennik_posilkow/', include(dziennik_posilkow.urls, namespace='dziennik_posilkow')),
    url(r'^admin/', include(admin.site.urls)),
]

apps/dziennik_posilkow/urls.py
from django.conf.urls import patterns, url

from dziennik_posilkow import views

urlpatterns = [
  url(r'^$', views.home, name='home'),

  url(r'^zawodnik_view/(?P<pk>\d+)$', views.zawodnik_view, name='zawodnik_view'),
  url(r'^zawodnik_new$', views.zawodnik_create, name='zawodnik_new'),
  url(r'^zawodnik_edit/(?P<pk>\d+)$', views.zawodnik_update, name='zawodnik_edit'),
  url(r'^zawodnik_delete/(?P<pk>\d+)$', views.zawodnik_delete, name='zawodnik_delete'),

  url(r'^posilek_new/(?P<parent_pk>\d+)$', views.posilek_create, name='posilek_new'),
  url(r'^posilek_edit/(?P<pk>\d+)$', views.posilek_update, name='posilek_edit'),
  url(r'^posilek_delete/(?P<pk>\d+)$', views.posilek_delete, name='posilek_delete'),
]

apps/dziennik_posilkow/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Zawodnik(models.Model):
    imie = models.CharField(max_length=200)
    nazwisko = models.CharField(max_length=200)
    wiek = models.IntegerField()

    def __unicode__(self):
        return self.imie

    def get_absolute_url(self):
        return reverse('dziennik_posilkow:zawodnik_edit', kwargs={'pk': self.pk})


class Posilek(models.Model):
    zawodnik = models.ForeignKey(Zawodnik)
    produkt = models.CharField(max_length=200)
    ilosc = models.CharField(max_length=200)
    kalorie = models.IntegerField()

    def __unicode__(self):
        return "Posilek from: " + self.produkt

    def get_absolute_url(self):
        return reverse('dziennik_posilkow:posilek_edit', kwargs={'pk': self.pk})

apps/theme/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/dziennik_posilkow/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from dziennik_posilkow.models import Zawodnik, Posilek

# ========== Forms =========

class ZawodnikForm(ModelForm):
    class Meta:
        model = Zawodnik
        fields = ['imie', 'nazwisko', 'wiek']

class PosilekForm(ModelForm):
    class Meta:
        model = Posilek
        fields = ['produkt', 'ilosc', 'kalorie']


# ========== Home =========

def home(request, template_name='dziennik_posilkow/home.html'):
    zawodnicy = Zawodnik.objects.all()
    ctx = {}
    ctx['zawodnicy'] = zawodnicy
    return render(request, template_name, ctx)
    

# ========== Zawodnik CRUD =========

def zawodnik_view(request, pk, template_name='dziennik_posilkow/zawodnik_view.html'):
    zawodnik= get_object_or_404(Zawodnik, pk=pk)
    posilki = Posilek.objects.filter(zawodnik=zawodnik)
    ctx = {}
    ctx["zawodnik"] = zawodnik
    ctx["posilki"] = posilki
    return render(request, template_name, ctx)

def zawodnik_create(request, template_name='dziennik_posilkow/zawodnik_form.html'):
    form = ZawodnikForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('dziennik_posilkow:home')
    ctx = {}
    ctx["form"] = form
    return render(request, template_name, ctx)

def zawodnik_update(request, pk, template_name='dziennik_posilkow/zawodnik_form.html'):
    zawodnik= get_object_or_404(Zawodnik, pk=pk)
    form = ZawodnikForm(request.POST or None, instance=zawodnik)
    if form.is_valid():
        form.save()
        return redirect('dziennik_posilkow:home')
    ctx = {}
    ctx["form"] = form
    ctx["zawodnik"] = zawodnik
    return render(request, template_name, ctx)

def zawodnik_delete(request, pk, template_name='dziennik_posilkow/zawodnik_confirm_delete.html'):
    zawodnik= get_object_or_404(Zawodnik, pk=pk)    
    if request.method=='POST':
        zawodnik.delete()
        return redirect('dziennik_posilkow:home')
    ctx = {}
    ctx["object"] = zawodnik
    ctx["zawodnik"] = zawodnik
    return render(request, template_name, ctx)


# ========== Posilek CRUD =========

def posilek_create(request, parent_pk, template_name='dziennik_posilkow/posilek_form.html'):
    zawodnik = get_object_or_404(Zawodnik, pk=parent_pk)
    form = PosilekForm(request.POST or None)
    if form.is_valid():
        posilek = form.save(commit=False)
        posilek.zawodnik = zawodnik
        posilek.save()
        return redirect('dziennik_posilkow:zawodnik_view', parent_pk)
    ctx = {}
    ctx["form"] = form
    ctx["zawodnik"] = zawodnik
    return render(request, template_name, ctx)

def posilek_update(request, pk, template_name='dziennik_posilkow/posilek_form.html'):
    posilek = get_object_or_404(Posilek, pk=pk)
    parent_pk = posilek.zawodnik.pk
    form = PosilekForm(request.POST or None, instance=posilek)
    if form.is_valid():
        form.save()
        return redirect('dziennik_posilkow:zawodnik_view', parent_pk)
    ctx = {}
    ctx["form"] = form
    ctx["zawodnik"] = posilek.zawodnik
    return render(request, template_name, ctx)

def posilek_delete(request, pk, template_name='dziennik_posilkow/posilek_confirm_delete.html'):
    posilek = get_object_or_404(Posilek, pk=pk)    
    parent_pk = posilek.zawodnik.pk
    if request.method=='POST':
        posilek.delete()
        return redirect('dziennik_posilkow:zawodnik_view', parent_pk)
    ctx = {}
    ctx["object"] = posilek
    ctx["zawodnik"] = posilek.zawodnik
    return render(request, template_name, ctx)

apps/theme/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

def home(request, template_name='home.html'):
    return render(request, template_name)

apps/dziennik_posilkow/templates/dziennik_posilkow/home.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% extends "base.html" %}

{% block title %}Zawodnik List{% endblock %}

{% block content %}
{% include "dziennik_posilkow/nav.html" %}

<h2>Zawodnicy i posilki</h2>

<ul>
    {% for zawodnik in zawodnicy %}
	<div class="container">
	<div class="jumbotron">
		 <ul class="list-group">
			<li class="list-group-item" >{{ zawodnik.imie }}</li>
			<li class="list-group-item">{{ zawodnik.nazwisko }}</li>
			<li class="list-group-item">{{ zawodnik.wiek }} Lat</li>
		</ul> 
	<div class="btn-group" role="group" aria-label="...">
					<a href="{% url 'dziennik_posilkow:zawodnik_view' zawodnik.id %}" class="btn btn-default" role="button">pokaz</a>
					<a href="{% url 'dziennik_posilkow:zawodnik_edit' zawodnik.id %}" class="btn btn-default" role="button">edytuj</a>
					<a href="{% url 'dziennik_posilkow:zawodnik_delete' zawodnik.id %}" class="btn btn-danger" role="button">usun</a>
			</div>
		</div>
	</div>
		
    {% endfor %}
</ul>

<a href="{% url 'dziennik_posilkow:zawodnik_new' %}" class="btn btn-default" role="button">Nowy zawodnik</a>
{% endblock %}

apps/dziennik_posilkow/templates/dziennik_posilkow/nav.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<h2>
<a href="{% url 'dziennik_posilkow:home' %}">Strona Domowa</a>
{% if zawodnik %}
&gt; <a href="{% url 'dziennik_posilkow:zawodnik_view' zawodnik.id %}">{{ zawodnik.imie }}</a>
{% endif %}
{% if title %}
&gt; {{ title }}
{% endif %}
</h2>

apps/dziennik_posilkow/templates/dziennik_posilkow/posilek_confirm_delete.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% extends "base.html" %}


{% block content %}
{% include "dziennik_posilkow/nav.html" with zawodnik=zawodnik title="Usun Posilek" %}
<form method="post">{% csrf_token %}
    Jestes pewien ze chcesz usunac posilek ?
    <input type="submit" value="Potwierdz" />
</form>
{% endblock %}

apps/dziennik_posilkow/templates/dziennik_posilkow/posilek_form.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% extends "base.html" %}


{% block content %}
{% include "dziennik_posilkow/nav.html" with zawodnik=zawodnik title="Edytuj/Dodaj Posilek" %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Potwierdz" />
</form>
{% endblock %}

apps/dziennik_posilkow/templates/dziennik_posilkow/zawodnik_confirm_delete.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% extends "base.html" %}

{% block content %}
{% include "dziennik_posilkow/nav.html" with zawodnik=zawodnik title="Usun" %}

<form method="post">{% csrf_token %}
    Jestes pewien ze chcesz usunac zawodnika ?
	<input type="submit" class="btn btn-danger" value="Potwierdz">
</form>
{% endblock %}

apps/dziennik_posilkow/templates/dziennik_posilkow/zawodnik_form.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% extends "base.html" %}


{% block content %}
{% include "dziennik_posilkow/nav.html" with zawodnik=zawodnik title="Edytuj/Dodaj Zawodnika" %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Potwierdz" />
</form>

<!-- <form method="post">{% csrf_token %}
  <div class="form-group">
    <label for="imie">Imie</label>
    <input type="text" class="form-control" id="imie" placeholder="Imie">
   </div>
  <div class="form-group">
    <label for="nazwisko">Nazwisko</label>
    <input type="text" class="form-control" id="nazwisko" placeholder="Nazwisko">
   </div>
   <div class="form-group">
    <label for="wiek">Wiek</label>
    <input type="text" class="form-control" id="wiek" placeholder="Wiek">
   </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
  <input type="submit" value="Potwierdz" />
</form> -->

{% endblock %}

apps/dziennik_posilkow/templates/dziennik_posilkow/zawodnik_view.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% extends "base.html" %}


{% block content %}
{% include "dziennik_posilkow/nav.html" with zawodnik=zawodnik title="Podglad" %}

<div class="container">
	<div class="jumbotron">

<ul class="list-group">
			<li class="list-group-item" >{{ zawodnik.imie }}</li>
			<li class="list-group-item">{{ zawodnik.nazwisko }}</li>
			<li class="list-group-item">{{ zawodnik.wiek }} Lat</li>
		</ul> 

<h2>Posiłki</h2>
<ul>
    {% for posilek in posilki %}
    <li>

	<ul class="list-group">
			<li class="list-group-item" >{{ posilek.produkt }}</li>
			<li class="list-group-item">{{ posilek.ilosc}}</li>
			<li class="list-group-item">{{ posilek.kalorie}} Kalorii</li>
		</ul> 
	
		<div class="btn-group" role="group" aria-label="...">
			
					<a href="{% url 'dziennik_posilkow:posilek_edit' posilek.id %}" class="btn btn-default" role="button">edytuj</a>
					<a href="{% url 'dziennik_posilkow:posilek_delete' posilek.id %}" class="btn btn-danger" role="button">usun</a>
			</div>

    </li>
    {% endfor %}
</ul>
</div>
</div>

<a href="{% url 'dziennik_posilkow:posilek_new' zawodnik.id %}" class="btn btn-default" >Nowy posilek</a>
{% endblock %}

apps/theme/templates/base.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django CRUD: {% block title %}Welcome{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" media="all" rel="stylesheet" />
</head>

<body>
<div id="wrapper">
    <h1><a href="{% url 'home' %}">Adam Chlebba Python CRUD Project</a></h1>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</div><!-- wrapper -->
</body>
</html>

apps/theme/templates/home.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% extends "base.html" %}

{% block content %}

<ul>

<li><a href="{% url 'dziennik_posilkow:home' %}">Dziennik Posilkow</a></li>

</ul>

{% endblock %}